{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "from globals import * \n",
    "import fileinput\n",
    "import re\n",
    "\n",
    "input_file = open(\"globals_backup.py\", \"r\")\n",
    "import fileinput\n",
    "import re\n",
    "\n",
    "for line in fileinput.input():\n",
    "    line = re.sub(r'globals()\\\\['test']*', r'\\1', line.rstrip())\n",
    "    print(line)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "## Scale Value Experiment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "set_var('EPOCHS', 50)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-01-04 02:32:13.287329: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n",
      "Speed Challenge\n",
      "2021-01-04 02:32:15.854981: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2021-01-04 02:32:15.855316: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1\n",
      "2021-01-04 02:32:15.855375: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: UNKNOWN ERROR (-1)\n",
      "2021-01-04 02:32:15.855400: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (e01c8c19c2aa): /proc/driver/nvidia/version does not exist\n",
      "2021-01-04 02:32:15.857953: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "Model: \"sequential\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "flatten (Flatten)            (None, 20)                0         \n",
      "_________________________________________________________________\n",
      "dense (Dense)                (None, 64)                1344      \n",
      "_________________________________________________________________\n",
      "dense_1 (Dense)              (None, 32)                2080      \n",
      "_________________________________________________________________\n",
      "dense_2 (Dense)              (None, 16)                528       \n",
      "_________________________________________________________________\n",
      "dense_3 (Dense)              (None, 1)                 17        \n",
      "=================================================================\n",
      "Total params: 3,969\n",
      "Trainable params: 3,969\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n",
      "None\n",
      "(163190, 2)\n",
      "(16319, 10, 2)\n",
      "2021-01-04 02:32:15.966732: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.\n",
      "2021-01-04 02:32:15.966803: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.\n",
      "2021-01-04 02:32:15.966900: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.\n",
      "2021-01-04 02:32:16.067558: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)\n",
      "2021-01-04 02:32:16.068143: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 1992005000 Hz\n",
      "Epoch 1/100\n",
      " 1/64 [..............................] - ETA: 28s - loss: 0.1585 - mean_squared_error: 0.15852021-01-04 02:32:16.540081: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.\n",
      "2021-01-04 02:32:16.540146: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.\n",
      "2021-01-04 02:32:16.545443: I tensorflow/core/profiler/lib/profiler_session.cc:71] Profiler session collecting data.\n",
      "2021-01-04 02:32:16.546400: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.\n",
      "2021-01-04 02:32:16.573655: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16\n",
      "2021-01-04 02:32:16.587429: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for trace.json.gz to ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16/e01c8c19c2aa.trace.json.gz\n",
      "2021-01-04 02:32:16.601864: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16\n",
      "2021-01-04 02:32:16.611057: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for memory_profile.json.gz to ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16/e01c8c19c2aa.memory_profile.json.gz\n",
      "2021-01-04 02:32:16.730878: I tensorflow/core/profiler/rpc/client/capture_profile.cc:251] Creating directory: ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16Dumped tool data for xplane.pb to ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16/e01c8c19c2aa.xplane.pb\n",
      "Dumped tool data for overview_page.pb to ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16/e01c8c19c2aa.overview_page.pb\n",
      "Dumped tool data for input_pipeline.pb to ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16/e01c8c19c2aa.input_pipeline.pb\n",
      "Dumped tool data for tensorflow_stats.pb to ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16/e01c8c19c2aa.tensorflow_stats.pb\n",
      "Dumped tool data for kernel_stats.pb to ./speed_modules/logs/20210104-023215/train/plugins/profile/2021_01_04_02_32_16/e01c8c19c2aa.kernel_stats.pb\n",
      "\n",
      "64/64 [==============================] - 1s 13ms/step - loss: 0.0414 - mean_squared_error: 0.0414 - val_loss: 0.0179 - val_mean_squared_error: 0.0179\n",
      "\n",
      "Epoch 00001: saving model to speed_modules/speed_predictor_model\n",
      "2021-01-04 02:32:17.763892: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.\n",
      "Epoch 2/100\n",
      "64/64 [==============================] - 0s 6ms/step - loss: 0.0133 - mean_squared_error: 0.0133 - val_loss: 0.0070 - val_mean_squared_error: 0.0070\n",
      "\n",
      "Epoch 00002: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 3/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0062 - mean_squared_error: 0.0062 - val_loss: 0.0056 - val_mean_squared_error: 0.0056\n",
      "\n",
      "Epoch 00003: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 4/100\n",
      "64/64 [==============================] - 0s 7ms/step - loss: 0.0051 - mean_squared_error: 0.0051 - val_loss: 0.0050 - val_mean_squared_error: 0.0050\n",
      "\n",
      "Epoch 00004: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 5/100\n",
      "64/64 [==============================] - 0s 6ms/step - loss: 0.0045 - mean_squared_error: 0.0045 - val_loss: 0.0046 - val_mean_squared_error: 0.0046\n",
      "\n",
      "Epoch 00005: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 6/100\n",
      "64/64 [==============================] - 0s 6ms/step - loss: 0.0042 - mean_squared_error: 0.0042 - val_loss: 0.0044 - val_mean_squared_error: 0.0044\n",
      "\n",
      "Epoch 00006: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 7/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0040 - mean_squared_error: 0.0040 - val_loss: 0.0042 - val_mean_squared_error: 0.0042\n",
      "\n",
      "Epoch 00007: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 8/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0037 - mean_squared_error: 0.0037 - val_loss: 0.0040 - val_mean_squared_error: 0.0040\n",
      "\n",
      "Epoch 00008: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 9/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0036 - mean_squared_error: 0.0036 - val_loss: 0.0040 - val_mean_squared_error: 0.0040\n",
      "\n",
      "Epoch 00009: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 10/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0035 - mean_squared_error: 0.0035 - val_loss: 0.0039 - val_mean_squared_error: 0.0039\n",
      "\n",
      "Epoch 00010: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 11/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0033 - mean_squared_error: 0.0033 - val_loss: 0.0038 - val_mean_squared_error: 0.0038\n",
      "\n",
      "Epoch 00011: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 12/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0033 - mean_squared_error: 0.0033 - val_loss: 0.0037 - val_mean_squared_error: 0.0037\n",
      "\n",
      "Epoch 00012: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 13/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0032 - mean_squared_error: 0.0032 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "\n",
      "Epoch 00013: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 14/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0031 - mean_squared_error: 0.0031 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "\n",
      "Epoch 00014: saving model to speed_modules/speed_predictor_model\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 15/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0031 - mean_squared_error: 0.0031 - val_loss: 0.0035 - val_mean_squared_error: 0.0035\n",
      "\n",
      "Epoch 00015: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 16/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0030 - mean_squared_error: 0.0030 - val_loss: 0.0034 - val_mean_squared_error: 0.0034\n",
      "\n",
      "Epoch 00016: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 17/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0029 - mean_squared_error: 0.0029 - val_loss: 0.0034 - val_mean_squared_error: 0.0034\n",
      "\n",
      "Epoch 00017: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 18/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0029 - mean_squared_error: 0.0029 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "\n",
      "Epoch 00018: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 19/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0028 - mean_squared_error: 0.0028 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "\n",
      "Epoch 00019: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 20/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0028 - mean_squared_error: 0.0028 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "\n",
      "Epoch 00020: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 21/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0028 - mean_squared_error: 0.0028 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "\n",
      "Epoch 00021: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 22/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0027 - mean_squared_error: 0.0027 - val_loss: 0.0033 - val_mean_squared_error: 0.0033\n",
      "\n",
      "Epoch 00022: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 23/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0027 - mean_squared_error: 0.0027 - val_loss: 0.0032 - val_mean_squared_error: 0.0032\n",
      "\n",
      "Epoch 00023: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 24/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0026 - mean_squared_error: 0.0026 - val_loss: 0.0032 - val_mean_squared_error: 0.0032\n",
      "\n",
      "Epoch 00024: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 25/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0027 - mean_squared_error: 0.0027 - val_loss: 0.0031 - val_mean_squared_error: 0.0031\n",
      "\n",
      "Epoch 00025: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 26/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0026 - mean_squared_error: 0.0026 - val_loss: 0.0031 - val_mean_squared_error: 0.0031\n",
      "\n",
      "Epoch 00026: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 27/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0026 - mean_squared_error: 0.0026 - val_loss: 0.0032 - val_mean_squared_error: 0.0032\n",
      "\n",
      "Epoch 00027: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 28/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0026 - mean_squared_error: 0.0026 - val_loss: 0.0031 - val_mean_squared_error: 0.0031\n",
      "\n",
      "Epoch 00028: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 29/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0031 - val_mean_squared_error: 0.0031\n",
      "\n",
      "Epoch 00029: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 30/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0030 - val_mean_squared_error: 0.0030\n",
      "\n",
      "Epoch 00030: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 31/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0030 - val_mean_squared_error: 0.0030\n",
      "\n",
      "Epoch 00031: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 32/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0024 - mean_squared_error: 0.0024 - val_loss: 0.0030 - val_mean_squared_error: 0.0030\n",
      "\n",
      "Epoch 00032: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 33/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0025 - mean_squared_error: 0.0025 - val_loss: 0.0030 - val_mean_squared_error: 0.0030\n",
      "\n",
      "Epoch 00033: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 34/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0024 - mean_squared_error: 0.0024 - val_loss: 0.0030 - val_mean_squared_error: 0.0030\n",
      "\n",
      "Epoch 00034: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 35/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0024 - mean_squared_error: 0.0024 - val_loss: 0.0029 - val_mean_squared_error: 0.0029\n",
      "\n",
      "Epoch 00035: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 36/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0023 - mean_squared_error: 0.0023 - val_loss: 0.0029 - val_mean_squared_error: 0.0029\n",
      "\n",
      "Epoch 00036: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 37/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0023 - mean_squared_error: 0.0023 - val_loss: 0.0029 - val_mean_squared_error: 0.0029\n",
      "\n",
      "Epoch 00037: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 38/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0023 - mean_squared_error: 0.0023 - val_loss: 0.0029 - val_mean_squared_error: 0.0029\n",
      "\n",
      "Epoch 00038: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 39/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0023 - mean_squared_error: 0.0023 - val_loss: 0.0029 - val_mean_squared_error: 0.0029\n",
      "\n",
      "Epoch 00039: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 40/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0023 - mean_squared_error: 0.0023 - val_loss: 0.0030 - val_mean_squared_error: 0.0030\n",
      "\n",
      "Epoch 00040: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 41/100\n",
      "64/64 [==============================] - 0s 3ms/step - loss: 0.0023 - mean_squared_error: 0.0023 - val_loss: 0.0029 - val_mean_squared_error: 0.0029\n",
      "\n",
      "Epoch 00041: saving model to speed_modules/speed_predictor_model\n",
      "^C\n",
      "Traceback (most recent call last):\n",
      "  File \"speedchallenge.py\", line 30, in <module>\n",
      "    net.main(args)\n",
      "  File \"speedchallenge.py\", line 9, in main\n",
      "    self.train()\n",
      "  File \"speedchallenge.py\", line 14, in train\n",
      "    train()\n",
      "  File \"/tf/notebooks/speed_modules/train.py\", line 73, in train\n",
      "    model.fit(X_train, Y_train, batch_size=BATCH_SIZE, epochs=EPOCHS,  validation_data=(X_val, Y_val), callbacks=callbacks_list)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py\", line 1145, in fit\n",
      "    callbacks.on_epoch_end(epoch, epoch_logs)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py\", line 428, in on_epoch_end\n",
      "    callback.on_epoch_end(epoch, logs)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py\", line 1344, in on_epoch_end\n",
      "    self._save_model(epoch=epoch, logs=logs)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py\", line 1408, in _save_model\n",
      "    self.model.save(filepath, overwrite=True, options=self._options)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py\", line 2002, in save\n",
      "    signatures, options, save_traces)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py\", line 157, in save_model\n",
      "    signatures, options, save_traces)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save.py\", line 89, in save\n",
      "    save_lib.save(model, filepath, signatures, options)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py\", line 1042, in save\n",
      "    utils_impl.get_variables_path(export_dir), options=ckpt_options)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py\", line 1217, in save\n",
      "    file_prefix_tensor, object_graph_tensor, options)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py\", line 1162, in _save_cached_when_graph_building\n",
      "    save_op = saver.save(file_prefix, options=options)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/functional_saver.py\", line 300, in save\n",
      "    return save_fn()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/functional_saver.py\", line 274, in save_fn\n",
      "    sharded_saves.append(saver.save(shard_prefix, options))\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/functional_saver.py\", line 83, in save\n",
      "    return io_ops.save_v2(file_prefix, tensor_names, tensor_slices, tensors)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_io_ops.py\", line 1716, in save_v2\n",
      "    ctx=_ctx)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_io_ops.py\", line 1736, in save_v2_eager_fallback\n",
      "    ctx=ctx, name=name)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py\", line 60, in quick_execute\n",
      "    inputs, attrs, num_outputs)\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "set_var('SCALE_OUTPUT', 100)\n",
    "!python speedchallenge.py --mode train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-01-04 02:33:02.851931: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n",
      "Speed Challenge\n",
      "2021-01-04 02:33:05.391358: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2021-01-04 02:33:05.391569: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1\n",
      "2021-01-04 02:33:05.391611: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: UNKNOWN ERROR (-1)\n",
      "2021-01-04 02:33:05.391654: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (e01c8c19c2aa): /proc/driver/nvidia/version does not exist\n",
      "2021-01-04 02:33:05.392984: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "Model: \"sequential\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "flatten (Flatten)            (None, 20)                0         \n",
      "_________________________________________________________________\n",
      "dense (Dense)                (None, 64)                1344      \n",
      "_________________________________________________________________\n",
      "dense_1 (Dense)              (None, 32)                2080      \n",
      "_________________________________________________________________\n",
      "dense_2 (Dense)              (None, 16)                528       \n",
      "_________________________________________________________________\n",
      "dense_3 (Dense)              (None, 1)                 17        \n",
      "=================================================================\n",
      "Total params: 3,969\n",
      "Trainable params: 3,969\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n",
      "None\n",
      "(163190, 2)\n",
      "(16319, 10, 2)\n",
      "2021-01-04 02:33:05.509312: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.\n",
      "2021-01-04 02:33:05.509389: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.\n",
      "2021-01-04 02:33:05.509450: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.\n",
      "2021-01-04 02:33:05.628664: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)\n",
      "2021-01-04 02:33:05.629130: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 1992005000 Hz\n",
      "Epoch 1/100\n",
      " 1/64 [..............................] - ETA: 31s - loss: 0.0195 - mean_squared_error: 0.01952021-01-04 02:33:06.155622: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.\n",
      "2021-01-04 02:33:06.155680: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.\n",
      "2021-01-04 02:33:06.158904: I tensorflow/core/profiler/lib/profiler_session.cc:71] Profiler session collecting data.\n",
      "2021-01-04 02:33:06.159807: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.\n",
      "2021-01-04 02:33:06.190083: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./speed_modules/logs/20210104-023305/train/plugins/profile/2021_01_04_02_33_06\n",
      "2021-01-04 02:33:06.208470: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for trace.json.gz to ./speed_modules/logs/20210104-023305/train/plugins/profile/2021_01_04_02_33_06/e01c8c19c2aa.trace.json.gz\n",
      "2021-01-04 02:33:06.220353: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./speed_modules/logs/20210104-023305/train/plugins/profile/2021_01_04_02_33_06\n",
      "2021-01-04 02:33:06.226868: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for memory_profile.json.gz to ./speed_modules/logs/20210104-023305/train/plugins/profile/2021_01_04_02_33_06/e01c8c19c2aa.memory_profile.json.gz\n",
      "13/64 [=====>........................] - ETA: 1s - loss: 0.0161 - mean_squared_error: 0.0161^C\n",
      "Traceback (most recent call last):\n",
      "  File \"speedchallenge.py\", line 30, in <module>\n",
      "    net.main(args)\n",
      "  File \"speedchallenge.py\", line 9, in main\n",
      "    self.train()\n",
      "  File \"speedchallenge.py\", line 14, in train\n",
      "    train()\n",
      "  File \"/tf/notebooks/speed_modules/train.py\", line 73, in train\n",
      "    model.fit(X_train, Y_train, batch_size=BATCH_SIZE, epochs=EPOCHS,  validation_data=(X_val, Y_val), callbacks=callbacks_list)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py\", line 1100, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py\", line 830, in __call__\n",
      "    new_tracing_count = self.experimental_get_tracing_count()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py\", line 787, in experimental_get_tracing_count\n",
      "    def experimental_get_tracing_count(self):\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "set_var('SCALE_OUTPUT', 10)\n",
    "!python speedchallenge.py --mode train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-01-04 02:33:07.531195: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n",
      "Speed Challenge\n",
      "2021-01-04 02:33:11.057640: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2021-01-04 02:33:11.058311: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1\n",
      "2021-01-04 02:33:11.058395: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: UNKNOWN ERROR (-1)\n",
      "2021-01-04 02:33:11.058512: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (e01c8c19c2aa): /proc/driver/nvidia/version does not exist\n",
      "2021-01-04 02:33:11.061310: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "Model: \"sequential\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "flatten (Flatten)            (None, 20)                0         \n",
      "_________________________________________________________________\n",
      "dense (Dense)                (None, 64)                1344      \n",
      "_________________________________________________________________\n",
      "dense_1 (Dense)              (None, 32)                2080      \n",
      "_________________________________________________________________\n",
      "dense_2 (Dense)              (None, 16)                528       \n",
      "_________________________________________________________________\n",
      "dense_3 (Dense)              (None, 1)                 17        \n",
      "=================================================================\n",
      "Total params: 3,969\n",
      "Trainable params: 3,969\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n",
      "None\n",
      "(163190, 2)\n",
      "(16319, 10, 2)\n",
      "2021-01-04 02:33:11.294466: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.\n",
      "2021-01-04 02:33:11.294624: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.\n",
      "2021-01-04 02:33:11.294735: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.\n",
      "2021-01-04 02:33:11.508955: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)\n",
      "2021-01-04 02:33:11.509552: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 1992005000 Hz\n",
      "Epoch 1/100\n",
      " 1/64 [..............................] - ETA: 59s - loss: 0.0207 - mean_squared_error: 0.02072021-01-04 02:33:12.497629: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.\n",
      "2021-01-04 02:33:12.497697: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.\n",
      "2021-01-04 02:33:12.501980: I tensorflow/core/profiler/lib/profiler_session.cc:71] Profiler session collecting data.\n",
      "2021-01-04 02:33:12.503185: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.\n",
      "2021-01-04 02:33:12.526226: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12\n",
      "2021-01-04 02:33:12.544167: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for trace.json.gz to ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12/e01c8c19c2aa.trace.json.gz\n",
      "2021-01-04 02:33:12.559224: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12\n",
      "2021-01-04 02:33:12.567475: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for memory_profile.json.gz to ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12/e01c8c19c2aa.memory_profile.json.gz\n",
      "2021-01-04 02:33:12.674258: I tensorflow/core/profiler/rpc/client/capture_profile.cc:251] Creating directory: ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12Dumped tool data for xplane.pb to ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12/e01c8c19c2aa.xplane.pb\n",
      "Dumped tool data for overview_page.pb to ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12/e01c8c19c2aa.overview_page.pb\n",
      "Dumped tool data for input_pipeline.pb to ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12/e01c8c19c2aa.input_pipeline.pb\n",
      "Dumped tool data for tensorflow_stats.pb to ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12/e01c8c19c2aa.tensorflow_stats.pb\n",
      "Dumped tool data for kernel_stats.pb to ./speed_modules/logs/20210104-023311/train/plugins/profile/2021_01_04_02_33_12/e01c8c19c2aa.kernel_stats.pb\n",
      "\n",
      "64/64 [==============================] - 2s 15ms/step - loss: 0.0124 - mean_squared_error: 0.0124 - val_loss: 0.0054 - val_mean_squared_error: 0.0054\n",
      "\n",
      "Epoch 00001: saving model to speed_modules/speed_predictor_model\n",
      "2021-01-04 02:33:13.619857: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.\n",
      "Epoch 2/100\n",
      "64/64 [==============================] - 0s 6ms/step - loss: 0.0049 - mean_squared_error: 0.0049 - val_loss: 0.0043 - val_mean_squared_error: 0.0043\n",
      "\n",
      "Epoch 00002: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 3/100\n",
      "64/64 [==============================] - 0s 7ms/step - loss: 0.0040 - mean_squared_error: 0.0040 - val_loss: 0.0039 - val_mean_squared_error: 0.0039\n",
      "\n",
      "Epoch 00003: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 4/100\n",
      "64/64 [==============================] - 1s 11ms/step - loss: 0.0036 - mean_squared_error: 0.0036 - val_loss: 0.0038 - val_mean_squared_error: 0.0038\n",
      "\n",
      "Epoch 00004: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 5/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0034 - mean_squared_error: 0.0034 - val_loss: 0.0036 - val_mean_squared_error: 0.0036\n",
      "\n",
      "Epoch 00005: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 6/100\n",
      "64/64 [==============================] - 0s 4ms/step - loss: 0.0032 - mean_squared_error: 0.0032 - val_loss: 0.0035 - val_mean_squared_error: 0.0035\n",
      "\n",
      "Epoch 00006: saving model to speed_modules/speed_predictor_model\n",
      "Epoch 7/100\n",
      "29/64 [============>.................] - ETA: 0s - loss: 0.0031 - mean_squared_error: 0.0031^C\n",
      "Traceback (most recent call last):\n",
      "  File \"speedchallenge.py\", line 30, in <module>\n",
      "    net.main(args)\n",
      "  File \"speedchallenge.py\", line 9, in main\n",
      "    self.train()\n",
      "  File \"speedchallenge.py\", line 14, in train\n",
      "    train()\n",
      "  File \"/tf/notebooks/speed_modules/train.py\", line 73, in train\n",
      "    model.fit(X_train, Y_train, batch_size=BATCH_SIZE, epochs=EPOCHS,  validation_data=(X_val, Y_val), callbacks=callbacks_list)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py\", line 1100, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py\", line 828, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py\", line 855, in _call\n",
      "    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py\", line 2943, in __call__\n",
      "    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py\", line 1919, in _call_flat\n",
      "    ctx, args, cancellation_manager=cancellation_manager))\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py\", line 560, in call\n",
      "    ctx=ctx)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py\", line 60, in quick_execute\n",
      "    inputs, attrs, num_outputs)\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "set_var('SCALE_OUTPUT', 1)\n",
    "!python speedchallenge.py --mode train"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
